create table users(
    id int primary key generated by default as identity,
    name varchar(255) not null,
    email varchar(255) not null,
    login varchar(255) not null,
    password varchar(255) not null
)